# Generated by Django 3.1.5 on 2021-01-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_separated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='is_separating',
            field=models.BooleanField(default=False),
        ),
    ]
