# Generated by Django 3.1.5 on 2021-01-22 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='melody',
        ),
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
        migrations.RemoveField(
            model_name='song',
            name='voice',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
